import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import TopBar from "@/components/layout/TopBar";
// import Decor from "@/components/layout/Decor";
import '@rainbow-me/rainbowkit/styles.css'
import dynamic from 'next/dynamic'

const TopBarDynamic = dynamic(() => import ('@/components/layout/TopBar'), {ssr: false})

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body className="relative">
        <Providers>
          <TopBarDynamic/>
          {children}
        </Providers>
      </body>
    </html>
  );
}

export default RootLayout;
